# Generated by Django 5.1.1 on 2024-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_robloxuser_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robloxuser',
            name='banHistory',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='robloxuser',
            name='robloxID',
            field=models.CharField(default=1234, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robloxuser',
            name='username',
            field=models.CharField(default='1234', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
