# Generated by Django 5.1.1 on 2024-10-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_robloxuser_banhistory_robloxuser_robloxid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robloxuser',
            name='username',
        ),
        migrations.AddField(
            model_name='robloxuser',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
