# Generated by Django 5.1.1 on 2024-10-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_robloxuser_username_robloxuser_isbanned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robloxuser',
            options={'verbose_name': 'Members'},
        ),
    ]
