# Generated by Django 5.1.1 on 2024-10-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_robloxuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roblox_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account', to='registration.robloxuser'),
        ),
    ]
